from setuptools import setup, find_packages

setup(
    name="stock_news_sentiment",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "requests>=2.31.0",
        "python-dotenv>=1.0.0",
        "numpy>=1.24.3",
        "pandas>=2.0.2",
        "textblob>=0.17.1",
        "matplotlib>=3.7.1",
        "seaborn>=0.12.2",
        "scikit-learn>=1.2.2",
        "nltk>=3.8.1",
        "flask>=2.3.3",
        "sqlalchemy>=2.0.19",
        "psycopg2-binary>=2.9.7",
    ],
    author="Your Name",
    author_email="your.email@example.com",
    description="A tool for analyzing sentiment in stock-related news",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/Stock_News_Sentiment_Analyzer",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
) 